{
  "sksl": {
    "entrypoint": "background_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uResolutionX;\nuniform float uResolutionY;\nuniform float uOffsetX;\nuniform float uOffsetY;\nuniform float uTexWidth;\nuniform float uTexHeight;\nuniform float uZoom;\nuniform shader uStarTexture;\nuniform half2 uStarTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 resolution = vec2(uResolutionX, uResolutionY);\n    vec2 texSize = vec2(uTexWidth, uTexHeight);\n    vec2 center = resolution * 0.5;\n    vec2 fromCenter = fragCoord - center;\n    vec2 zoomedPos = center + (fromCenter / vec2(uZoom));\n    vec2 tiledPos = zoomedPos + vec2(uOffsetX, uOffsetY);\n    vec2 uv = mod(tiledPos, texSize) / texSize;\n    fragColor = uStarTexture.eval(uStarTexture_size * ( uv));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolutionX",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uResolutionY",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uOffsetX",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uOffsetY",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uTexWidth",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uTexHeight",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uZoom",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 7,
        "name": "uStarTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}